name: Deploy Fabric Items

on:
  push:
    branches:
      - master
      - 'release/*'
    paths:
      - 'fabric_items/**'
  pull_request:
    branches:
      - test
    paths:
      - 'fabric_items/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TARGET_ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .cicd/requirements.txt

      - name: Azure CLI login (device code)
        run: |
          az login --use-device-code

      # - name: Run authentication and deployment script
      #   run: |
      #     echo "Target Environment: $TARGET_ENVIRONMENT"
      #     python .cicd/authenticate_spn.py $TARGET_ENVIRONMENT

      - name: Get secret from Key Vault
        id: get_secret
        run: |
          STORAGE_KEY=$(az keyvault secret show \
            --vault-name snbpocvault \
            --name blobconnectionsecret \
            --query value -o tsv)
          echo "STORAGE_KEY=$STORAGE_KEY" >> $GITHUB_ENV


      - name: Run deployment with secrets
        run: |
          python .cicd/authenticate_spn.py $TARGET_ENVIRONMENT \
            --storage-key $STORAGE_KEY
        env:
          STORAGE_KEY: ${{ env.STORAGE_KEY }}


      - name: Upload error log
        if: always()
        uses: actions/upload-artifact@v4

        with:
          name: errorlog
          path: fabric_cicd.error.log
